/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRow: typeof import('bootstrap-vue-next')['BFormRow']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarbrand: typeof import('bootstrap-vue-next')['BNavbarbrand']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbartoggle: typeof import('bootstrap-vue-next')['BNavbartoggle']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPlaceholderCard: typeof import('bootstrap-vue-next')['BPlaceholderCard']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    BTransition: typeof import('bootstrap-vue-next')['BTransition']
    BuildForm: typeof import('./src/components/BuildForm.vue')['default']
    First: typeof import('./src/components/themes/First.vue')['default']
    NoResume: typeof import('./src/components/noResume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sydney: typeof import('./src/components/themes/Sydney.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColor: typeof import('bootstrap-vue-next')['vBColor']
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
